import Head from 'next/head'
import React from 'react'
import { ThemeProvider,createTheme } from '@mui/material/styles';
import NavBar from '../navbar/NavBar'
import styles from '@/styles/Home.module.css'
import Footer from '../footer/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';




function PageLayOut({children,title}) {


  return (
    <>
        {/* <ThemeProvider theme={theme}> */}
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
              {/* <Image src="/raizlogo.png" alt='logoraizcarpinteria' width={190} height={110} priority className={styles.imglogo}/> */}
              <NavBar />
              {/* <Link href='/'><ButtonLinkHome/></Link>    */}
            </header>

            <div >
                {children}
            </div>

            <footer >
              <Footer/>
            </footer>
        {/* </ThemeProvider> */}
        
    </>
  )
}

export default PageLayOut