import Head from 'next/head'
import React from 'react'
import { ThemeProvider,createTheme } from '@mui/material/styles';




function PageLayOut({children,title}) {

    const theme = createTheme({
        palette: {
          primary: {
            main: '#a97908'
          },
        },
      });

  return (
    <>
        <ThemeProvider theme={theme}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <main>
                {children}
            </main>
        </ThemeProvider>
        
    </>
  )
}

export default PageLayOut